print("Here's what we've got in the deck:")
print("All the Spades!!!")
print(Deck.allSpades)
print("All the Diamonds!!!")
print(Deck.allDiamonds)
print("All the Hearts!!!")
print(Deck.allHearts)
print("All the Clubs!!!")
print(Deck.allClubs)
print("And in case you've missed something - the whole deck!!!")
print(Deck.allCards)
