platform :ios, '9.3'

target 'Personal Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Personal Diary
    pod 'svovchyn2019', :path => '../svovchyn2019'
end
