let cardOne : Card = Card(color: Color.clubs, value: Value.jack)
let cardTwo : Card = Card(color: Color.hearts, value: Value.ace)
let cardThree : Card = Card(color: Color.clubs, value: Value.jack)
let cardFour : Card = Card(color: Color.diamonds, value: Value.ten)

print("The hands are:")
print("\(cardOne)\n\(cardTwo)\n\(cardThree)\n\(cardFour)")
print("Testing override function...")
print("........")
print(".......")
print(".....")
print("....")
print("...")
print("Does cardOne equal cardTwo...?")
print(cardOne.isEqual(cardTwo))
print("Maybe, cardThree and cardFour...?")
print(cardThree.isEqual(cardFour))
print("or cardOne and cardThree...?")
print(cardOne.isEqual(cardThree))
print("Testing overloaded operator...")
print("........")
print(".......")
print(".....")
print("....")
print("...")
print("cardFour equal cardThree...?")
print(cardFour == cardThree)
print("How about cardThree and cardOne...?")
print(cardThree == cardOne)
print("And maybe cardTwo and cardThree...?")
print(cardTwo == cardThree)
