var mixedDeck = Deck(deckIsMixed: true)
var orderedDeck = Deck(deckIsMixed: false)

print("Mixed deck")
for i in 0...5 {
    print(mixedDeck.cards[i])
}
print("Ordered deck")
for i in 0...5 {
    print(orderedDeck.cards[i])
}

print("Test of the description override...")
print(mixedDeck.cards)
print("Test of the draw() function...")
print("Deck before: \(orderedDeck.cards[0])")
print("Outs before:")
print(orderedDeck.outs)
var drawnCard = orderedDeck.draw()
print("Drawn card is \(drawnCard!)")
print("Deck after: \(orderedDeck.cards[0])")
print("Outs after:")
print(orderedDeck.outs)
print("fold() function test with the card that is in the outs...")
print("Deck before: \(orderedDeck.cards[0])")
print("Outs before:")
print(orderedDeck.outs)
print("Discards before:")
print(orderedDeck.disards)
orderedDeck.fold(c: drawnCard!)
print("Deck after: \(orderedDeck.cards[0])")
print("Outs after:")
print(orderedDeck.outs)
print("Discards after:")
print(orderedDeck.disards)

print("fold() function test with the card that is not in the outs...")
print("Deck before: \(orderedDeck.cards[0])")
print("Outs before:")
print(orderedDeck.outs)
print("Discards before:")
print(orderedDeck.disards)
var oneMoreDrawnCard = orderedDeck.draw()
orderedDeck.fold(c: orderedDeck.cards[7])
print("Deck after: \(orderedDeck.cards[0])")
print("Outs after:")
print(orderedDeck.outs)
print("Discards after:")
print(orderedDeck.disards)
